### ISSUE TITLE
make command not found

### ISSUE THREAD

**Issue by gabyrusu** [Sylius/Docker#27]
I'm running Docker (Compose 1.21.1) in Windows 10 Pro,  and "make" command doesn't seam to work:

>  make help
make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
+CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
+FullyQualifiedErrorId : CommandNotFoundException

Any help guys? Thanks!

**Comment by dzschille** [comment]
Your problem is most likely that the shell does not know where to find your make program. Make a internet search for "Windows 10 make : The term 'make' is not recognized as the name of a cmdlet" and you will find some possible solutions for your problem.

**Comment by gabyrusu** [comment]
I will do that! Thank you!
